# Задача 2.3. KNN

В этом задании Вам предлагается написать класс `KNN_classifier`, пригодный для решения задачи классификации (многоклассовой).

Мы предлагаем Вам шаблон класса. В этом шаблоне заполните тела функций `.fit` и `.predict`

В качестве функции близости используйте Евклидово расстояние между объектами (подробнее https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

Напоминание:

* Функция `.fit(x, y)` производит обучение модели. В рамках этой функции необходимо реализовать подбор оптимальных параметров модели/сконфигурировать модель для дальнейшего использования на основе данной тренировочной выборки, где x - это матрица признакового описания выборки, а y - вектор ответов.

* Функция `.predict(x)` осуществляет предсказание для каждого из объектов, чьи векторные описания представлены строками матрицы x. Выполняется строго после `.fit()`. Ради безопасности можно даже реализовать механизм отказа в виде выбрасывания специальной ошибки `UnfittedError` в случае попытки вызова функции `.predict()` до вызова функции `.fit()`.

Замечание: не изменяйте названия класса и его методов. Это приведёт к ошибке при исполнении Вашего кода в процессе проверки задания. Тем не менее, Вы можете дописать свои собственные методы, если это необходимо.

Шаблон класса:

In [53]:
import numpy as np


class KNN_classifier:
    def __init__(self, n_neighbors: int, **kwargs):
        self.K = n_neighbors
        self.points = []
        self.classes = []

    def euc_distance(self, point_1: np.array, point_2: np.array):
        """
        Вычисление евклидового расстояния между двумя точками.
        """
        vec = point_2 - point_1
        vec = vec*vec
        return np.sqrt(np.sum(vec))
    

    def fit(self, x: np.array, y: np.array):
        # TODO: напишите метод .fit() класса KNN_classifier
        # Эта функция принимает на вход два массива:
        # - x (набор признаков, массив размерности n x m, n - число объектов, m - размерность признакового описания)
        # - y (метки для обучения, одномерный массив размерности n)
        # Эта функция ничего не возвращает, она должна настроить внутренние параметры модели для дальнейшего использования
        # Подумайте, в чем заключается процесс обучения именно этого алгоритма?
        # Что этот алгоритм делает в тот момент, когда он получил обучающую выборку?
        # Реализуйте эту логику в коде
        n = len(y)

        # Подсчет и запоминание различных классов для классификации
        for cl in y:
            if cl not in self.classes:
                self.classes.append(cl)
        
        # Запоминаем points = [[[x_i], y]_j]
        #points = np.concatenate((x, y), axis=1).tolist()
        for i in range(n):
            self.points.append([x[i], y[i]])



    def predict(self, x: np.array):
        predictions = []
        # TODO: напишите метод .predict(x) класса KNN_classifier
        # Этот метод принимает на вход один массив x. Массив x - это двумерный массив объектов, для которых требуется получить предсказание
        # На выходе этой функции мы хотим получить одномерный массив predictions, размерности x.shape[0] (то есть для каждогго объекта массива x мы сделали своё предсказание)
        # Вспомните, как алгоритм KNN делает предсказание?
        # Реализуйте эту логику в коде
        sorted_points = []
        for i in range(len(x)):
            keyfunc = lambda P: self.euc_distance(P[0], x[i])
            sorted_points.append(sorted(self.points, key=keyfunc))

        for neigbors in sorted_points:
            res_count = [0 for _ in range(len(self.classes))]
            for neighb in neigbors[:self.K]:
                res_count[self.classes.index(neighb[1])] += 1
            mx = max(res_count)
            metka = self.classes[res_count.index(mx)]
            predictions.append(metka)

        return np.array(predictions)

## Примечания

1. Вы можете проверить правильность выполнения задания посредством сравнения полученных результатов с функцией из соответствующего модуля `sklearn`.

2. В рамках выполнения данного задания **запрещено** использовать функции из пакета `sklearn` и любого другого, кроме `numpy`. Код, использующий любые другие модули, не пройдёт тесты.

3. **Подсказка:** если Вы испытываете сложности с реализацией этого задания, начните выполнять его с написания функции `.predict`. В процессе написания этой функции Вы поймёте, что конкретно Вам требуется получить от обучающей выборки, какую информацию и в каком видед извлечь из неё. Затем реализуйте это в функции `.fit`

## Пример входных и выходных данных

In [54]:
X = np.array([[ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532],
       [-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076],
       [ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685],
       [ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583],
       [-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134],
       [-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809],
       [-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015],
       [-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543],
       [-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876],
       [-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]])
X

array([[ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532],
       [-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076],
       [ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685],
       [ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583],
       [-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134],
       [-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809],
       [-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015],
       [-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543],
       [-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876],
       [-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]])

In [55]:
y = np.array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])
y2 = np.array([3, 0, 0, 1, 0, 1, 0, 1, 0, 1])
y

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [56]:
knn = KNN_classifier(n_neighbors=3)

In [57]:
knn.fit(X, y)

In [58]:
knn.points

[[array([ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532]),
  np.int64(1)],
 [array([-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076]),
  np.int64(0)],
 [array([ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685]),
  np.int64(0)],
 [array([ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583]),
  np.int64(1)],
 [array([-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134]),
  np.int64(0)],
 [array([-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809]),
  np.int64(1)],
 [array([-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015]),
  np.int64(0)],
 [array([-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543]),
  np.int64(1)],
 [array([-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876]),
  np.int64(0)],
 [array([-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]),
  np.int64(1)]]

In [59]:
x_test = np.array([[-0.12489725,  0.65791923, -0.73112495,  1.42660225,  1.64728976],
       [ 0.01913388, -1.11351208, -0.63244098, -0.98121107,  0.38060892],
       [-0.92074931,  1.39812225,  0.39692147,  0.7717827 ,  0.44604002]])

In [60]:
knn.predict(x_test)

--->start
[[[array([-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]), np.int64(1)], [array([-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015]), np.int64(0)], [array([ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583]), np.int64(1)], [array([-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134]), np.int64(0)], [array([ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532]), np.int64(1)], [array([ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685]), np.int64(0)], [array([-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876]), np.int64(0)], [array([-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076]), np.int64(0)], [array([-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543]), np.int64(1)], [array([-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809]), np.int64(1)]], [[array([ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685]), np.int64(0)], [array(

array([1, 0, 0])